@startuml education_platform

  title Education Platform Domain

  class EducationPlatform

  package Content {
    class Itinerary
    EducationPlatform *--> Itinerary : baseItinerary
    EducationPlatform o--> "*" Itinerary

    abstract class Topic
    Itinerary o--> "*" Topic
    EducationPlatform *--> Topic : baseTopic

    class CompoundTopic
    Topic <|-down- CompoundTopic
    CompoundTopic o--> "*" Topic

    class SimpleTopic
    Topic <|-down- SimpleTopic

    package InformationUnits {
      abstract class InformationUnit
      SimpleTopic o--> "*" InformationUnit

      class Text
      InformationUnit <|-down- Text

      class Video
      InformationUnit <|-down- Video
      Video o--> "?" Text : transcription

      class Podcast
      InformationUnit <|-down- Podcast
      Video o--> "?" Podcast

      class Imagen
      InformationUnit <|-down- Imagen
    }

    package Knowledge {
      enum RelationType {
        + Inheritance
        + Composition
        + Aggregation
        + Association
        + Use
      }

      class Relation
      Relation *--> RelationType

      class Concept {
        + string name
      }
      Relation --> Concept : originConcept
      Relation --> Concept : destinationConcept

      class Definition
      Concept o--> "*" Definition

      class Justification {
        + bool isCorrect
      }
      Text <|-down- Justification
      Definition o--> "*" Justification

      class KnowledgeBase
      Itinerary *--> KnowledgeBase
      KnowledgeBase *--> "*" Concept
      KnowledgeBase *--> "*" Relation
    }

    package Exercises {
      class ProgrammingExercise
      SimpleTopic --> "*" ProgrammingExercise
      Itinerary o--> "*" ProgrammingExercise
      ProgrammingExercise --> KnowledgeBase

      class DomainStatement
      ProgrammingExercise o--> "*" DomainStatement : versionedStatements

      class Answer {
        + bool isCorrect
      }
      Text <|-down- Answer
      Answer <|-down- Definition
      DomainStatement o--> "*" Answer : applications
    }
  }

  ' ------------------- Chat and questions ------------------- '

  package Questions {
    class Conversation
    EducationPlatform o--> "*" Conversation

    abstract class Question
    EducationPlatform o--> "*" Question
    Conversation --> "*" Question
    Question --> Concept

    abstract class OpenQuestion
    Question <|-down- OpenQuestion
    OpenQuestion o--> Definition

    class FillDefinitionQuestion {
      + addDefinition() : void
    }
    class JustifyConceptQuestion {
      + addJustification() : void
    }
    OpenQuestion <|-down- JustifyConceptQuestion
    OpenQuestion <|-down- FillDefinitionQuestion

    class BestApplicationQuestion
    Question <|-down- BestApplicationQuestion
    BestApplicationQuestion ..> "2" Answer
    BestApplicationQuestion --> ProgrammingExercise

    enum ProgrammingPrinciple {
      + SingleResponsibility
      + AcyclicDependencies
      + CommonClosure
      + InterfaceSegregation
      + ...
    }
    BestApplicationQuestion *--> ProgrammingPrinciple
  }

  ' ------------------- Actors ------------------- '

  package Users {
    abstract class User
    EducationPlatform o--> "*" User

    class Teacher
    User <|-down- Teacher
    Itinerary --> Teacher : creator
    OpenQuestion --> "?" Teacher : checker

    class Student
    User <|-down- Student

    class Progress {
      + int timeInMinutesSpentInVideos
      + int timeInMinutesSpentInConversationQuestions
      + int percentageComplete
    }

    class StudentSubscription
    StudentSubscription *--> Student
    StudentSubscription *--> Progress
    Itinerary o--> "*" StudentSubscription : subscribers
    Conversation o--> StudentSubscription
  }

@enduml
